intervals_list: "bed/hg38_UCD_gene_regulatory.bed"
gnomad_v3.1.2_csv: "resources/finis/gNOMAD_v3.1.2/ABCA4_UCD_gnomad_v3.1.2.csv"
filter_tags: 
  -"""ClinVar_CLNSIG=='Likely pathogenic' or ClinVar_CLNSIG=='Pathogenic' or ClinVar_CLNSIG=='Conflicting_interpretations_of_pathogenicity'"""
  -"EAS_AF < 0.01"
  -"gnomAD_AF < 0.01"
  -"gnomAD_EAS_AF < 0.01"
  -"\`Allele Frequency\` < 0.01"
  -"\`Allele Frequency East Asian\` < 0.01"
  -"NARD_AF < 0.01"
  -"NARD_AF_MNG < 0.01"
  -"NARD_AF_KOR < 0.01"
  -"NARD_AF_JPN < 0.01"
  -"NARD_AF_CHN < 0.01"
  -"NARD_AF_HKG < 0.01"
  -"SpliceAI_highest_score > 0.5"'
csq: "Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|ALLELE_NUM|DISTANCE|STRAND|FLAGS|MINIMISED|SYMBOL_SOURCE|HGNC_ID|SOURCE|HGVS_OFFSET|HGVSg|AF|AFR_AF|AMR_AF|EAS_AF|EUR_AF|SAS_AF|gnomAD_AF|gnomAD_AFR_AF|gnomAD_AMR_AF|gnomAD_ASJ_AF|gnomAD_EAS_AF|gnomAD_FIN_AF|gnomAD_NFE_AF|gnomAD_OTH_AF|gnomAD_SAS_AF|MAX_AF|MAX_AF_POPS|CLIN_SIG|SOMATIC|PHENO|ClinVar|ClinVar_ClinVar|ClinVar_vcf|ClinVar_exact|ClinVar_0|ClinVar_AF_ESP|ClinVar_AF_EXAC|ClinVar_AF_TGP|ClinVar_ALLELEID|ClinVar_CLNDN|ClinVar_CLNDNINCL|ClinVar_CLNDISDB|ClinVar_CLNDISDBINCL|ClinVar_CLNHGVS|ClinVar_CLNREVSTAT|ClinVar_CLNSIG|ClinVar_CLNSIGCONF|ClinVar_CLNSIGINCL|ClinVar_CLNVC|ClinVar_CLNVCSO|ClinVar_CLNVI|ClinVar_DBVARID|ClinVar_GENEINFO|ClinVar_MC|ClinVar_ORIGIN|ClinVar_RS|ClinVar_SSR|NARD|NARD_AF|NARD_AF_MNG|NARD_AF_KOR|NARD_AF_JPN|NARD_AF_CHN|NARD_AF_HKG"
threads: 48